(define (caar (x)) (car (car x)))
(define (cadr (x)) (car (cdr x)))
(define (cdar (x)) (cdr (car x)))
(define (cddr (x)) (cdr (cdr x)))

(define (caaar (x)) (car (car (car x))))
(define (caadr (x)) (car (car (cdr x))))
(define (cadar (x)) (car (cdr (car x))))
(define (caddr (x)) (car (cdr (cdr x))))
(define (cdaar (x)) (cdr (car (car x))))
(define (cdadr (x)) (cdr (car (cdr x))))
(define (cddar (x)) (cdr (cdr (car x))))
(define (cdddr (x)) (cdr (cdr (cdr x))))

(define (caaaar (x)) (car (car (car (car x)))))
(define (caaadr (x)) (car (car (car (cdr x)))))
(define (caadar (x)) (car (car (cdr (car x)))))
(define (caaddr (x)) (car (car (cdr (cdr x)))))
(define (cadaar (x)) (car (cdr (car (car x)))))
(define (cadadr (x)) (car (cdr (car (cdr x)))))
(define (caddar (x)) (car (cdr (cdr (car x)))))
(define (cadddr (x)) (car (cdr (cdr (cdr x)))))
(define (cdaaar (x)) (cdr (car (car (car x)))))
(define (cdaadr (x)) (cdr (car (car (cdr x)))))
(define (cdadar (x)) (cdr (car (cdr (car x)))))
(define (cdaddr (x)) (cdr (car (cdr (cdr x)))))
(define (cddaar (x)) (cdr (cdr (car (car x)))))
(define (cddadr (x)) (cdr (cdr (car (cdr x)))))
(define (cdddar (x)) (cdr (cdr (cdr (car x)))))
(define (cddddr (x)) (cdr (cdr (cdr (cdr x)))))


(define (caaaaar (x)) (car (car (car (car (car x))))))
(define (caaaadr (x)) (car (car (car (car (cdr x))))))
(define (caaadar (x)) (car (car (car (cdr (car x))))))
(define (caaaddr (x)) (car (car (car (cdr (cdr x))))))
(define (caadaar (x)) (car (car (cdr (car (car x))))))
(define (caadadr (x)) (car (car (cdr (car (cdr x))))))
(define (caaddar (x)) (car (car (cdr (cdr (car x))))))
(define (caadddr (x)) (car (car (cdr (cdr (cdr x))))))
(define (cadaaar (x)) (car (cdr (car (car (car x))))))
(define (cadaadr (x)) (car (cdr (car (car (cdr x))))))
(define (cadadar (x)) (car (cdr (car (cdr (car x))))))
(define (cadaddr (x)) (car (cdr (car (cdr (cdr x))))))
(define (caddaar (x)) (car (cdr (cdr (car (car x))))))
(define (caddadr (x)) (car (cdr (cdr (car (cdr x))))))
(define (cadddar (x)) (car (cdr (cdr (cdr (car x))))))
(define (caddddr (x)) (car (cdr (cdr (cdr (cdr x))))))
(define (caaaaar (x)) (car (car (car (car (car x))))))
(define (cdaaadr (x)) (cdr (car (car (car (cdr x))))))
(define (cdaadar (x)) (cdr (car (car (cdr (car x))))))
(define (cdaaddr (x)) (cdr (car (car (cdr (cdr x))))))
(define (cdadaar (x)) (cdr (car (cdr (car (car x))))))
(define (cdadadr (x)) (cdr (car (cdr (car (cdr x))))))
(define (cdaddar (x)) (cdr (car (cdr (cdr (car x))))))
(define (cdadddr (x)) (cdr (car (cdr (cdr (cdr x))))))
(define (cddaaar (x)) (cdr (cdr (car (car (car x))))))
(define (cddaadr (x)) (cdr (cdr (car (car (cdr x))))))
(define (cddadar (x)) (cdr (cdr (car (cdr (car x))))))
(define (cddaddr (x)) (cdr (cdr (car (cdr (cdr x))))))
(define (cdddaar (x)) (cdr (cdr (cdr (car (car x))))))
(define (cdddadr (x)) (cdr (cdr (cdr (car (cdr x))))))
(define (cddddar (x)) (cdr (cdr (cdr (cdr (car x))))))
(define (cdddddr (x)) (cdr (cdr (cdr (cdr (cdr x))))))